### ISSUE TITLE
plot freq and recency vs holdout transactions 

### ISSUE THREAD

**Issue by danilyef** [wu-service-marketing/BTYDshiny#3]
I have a question about plot "freq and recency vs holdout transactions".

I found only 2 functions for 2 models:
bgnbd.PlotFreqVsConditionalExpectedFrequency
pnbd.PlotFreqVsConditionalExpectedFrequency

What about **mbgcnbd** and **mbgnbd** models?

**Comment by mplatzer** [comment]
yes, that's an open issue. see https://github.com/mplatzer/BTYDplus/issues/35 - feel free to tackle that, i.e. contribute to BTYDplus
