### ISSUE TITLE
plot tracking incremental & cumulative weekly

### ISSUE THREAD

**Issue by danilyef** [wu-service-marketing/BTYDshiny#5]
I want to ask, how can we compute the last argument in the following functions:
- pnbd.PlotTrackingCum(params, T.cal, T.tot, **actual.cu.tracking.data**)
- pnbd.PlotTrackingInc(params, T.cal, T.tot, **actual.inc.tracking.data**)

And as I understood for other models similar functions don't exist?

**Comment by mplatzer** [comment]
these can be created with `BTYD::elog2cum` and `BTYD::elog2inc`. see `?BTYD::mcmc.PlotTrackingCum` and `?BTYD::mbgcnbd.PlotTrackingCum` for examples how to call these methods.

(in case this answers your question, please go ahead, and then close this ticket; or just follow up with another comment)

**Comment by danilyef** [comment]
Thank you for the explanation!
One more question:
For mbgnbd model such function doesn't exist.
Can I use the function `BTYD::mbgcnbd.PlotTrackingCum` for this modell, or should I create the function for this modell?

**Comment by mplatzer** [comment]
yes, you can simply call `BTYD::mbgcnbd.PlotTrackingCum`

2016-09-27 13:04 GMT+02:00 danilyef notifications@github.com:
