### ISSUE TITLE
Error: "BTYDplus_xbgcnbd_exp_cpp" not available for .Call() for package "BTYDplus"

### ISSUE THREAD

**Issue by danilyef** [wu-service-marketing/BTYDshiny#7]
Whe I call some functions:
1)`mbgcnbd.PlotTrackingCum()`
2)`mbgcnbd.PlotTrackingInc()`
3)`mbgcnbd.ConditionalExpectedTransactions()` - only for Grocery data

The following error apears:
Error: "BTYDplus_xbgcnbd_exp_cpp" not available for .Call() for package "BTYDplus"

How can I fix that?

**Comment by mplatzer** [comment]
try doing a clean uninstall and reinstall of the BTYDplus package. make
sure that you are then using the latest version (0.11.1).

2016-09-30 17:57 GMT+02:00 danilyef notifications@github.com:
